import fetchFilterTags from "@/server/functions/fetchFilterTags";
import winkNLP from "wink-nlp";
import model from "wink-eng-lite-web-model";

const wink = winkNLP(model);
const its = wink.its;

type Tag = {
    tagId: number;
    tagName: string;
};

type CustomEntityMatch = {
    type: string;
    value: string;
    span: [number, number];
};

const tagAliases: Record<string, string[]> = {
    ai: [
        "ai",
        "artificial intelligence",
        "machine learning",
        "ml",
        "deep learning",
        "neural network",
        "neural networks",
        "llm",
        "llms",
        "large language model",
        "large language models",
        "gpt",
        "chatgpt",
        "openai",
        "claude",
        "gemini",
        "model",
        "models",
        "inference",
        "agent",
        "agents",
        "rag",
        "embedding",
        "embeddings",
    ],
    programming: [
        "programming",
        "coding",
        "code",
        "software",
        "software development",
        "developer",
        "developers",
        "engineering",
        "software engineering",
        "computer science",
        "compiler",
        "compilers",
        "runtime",
        "algorithm",
        "algorithms",
        "data structure",
        "data structures",
        "typescript",
        "javascript",
        "python",
        "rust",
        "golang",
        "go",
        "java",
        "c",
        "c++",
        "c#",
        "php",
        "ruby",
        "swift",
        "kotlin",
        "zig",
    ],
    webdev: [
        "webdev",
        "web dev",
        "web development",
        "website",
        "web app",
        "web application",
        "html",
        "css",
        "tailwind",
        "frontend",
        "backend",
        "fullstack",
        "full-stack",
        "react",
        "nextjs",
        "next js",
        "next.js",
        "vue",
        "svelte",
        "angular",
        "remix",
        "astro",
        "server components",
        "spa",
        "pwa",
    ],
    mobile: [
        "mobile",
        "ios",
        "android",
        "iphone",
        "ipad",
        "swift",
        "swiftui",
        "kotlin",
        "react native",
        "flutter",
        "mobile app",
        "app store",
        "play store",
    ],
    databases: [
        "database",
        "databases",
        "db",
        "sql",
        "nosql",
        "postgres",
        "postgresql",
        "mysql",
        "sqlite",
        "mongodb",
        "redis",
        "supabase",
        "firebase",
        "dynamodb",
        "clickhouse",
        "duckdb",
        "database index",
        "query",
        "queries",
        "orm",
        "migration",
        "migrations",
    ],
    devops: [
        "devops",
        "deployment",
        "deploy",
        "deploying",
        "ci",
        "cd",
        "ci/cd",
        "pipeline",
        "pipelines",
        "github actions",
        "build system",
        "release",
        "releases",
        "monitoring",
        "observability",
        "logging",
        "sre",
    ],
    cloud: [
        "cloud",
        "aws",
        "amazon web services",
        "gcp",
        "google cloud",
        "azure",
        "serverless",
        "lambda",
        "vercel",
        "netlify",
        "cloudflare",
        "edge",
        "edge computing",
        "hosting",
        "infrastructure",
        "infra",
    ],
    security: [
        "security",
        "secure",
        "vulnerability",
        "vulnerabilities",
        "exploit",
        "exploits",
        "malware",
        "ransomware",
        "phishing",
        "hacking",
        "hack",
        "breach",
        "breaches",
        "authentication",
        "authorization",
        "auth",
        "oauth",
        "password",
        "passwords",
        "encryption",
        "encrypted",
        "cryptography",
        "zero trust",
        "cve",
        "supply chain attack",
        "mpc",
        "multi party computation",
        "multiparty computation",
    ],
    privacy: [
        "privacy",
        "private",
        "anonymous",
        "anonymity",
        "tracking",
        "tracker",
        "trackers",
        "surveillance",
        "gdpr",
        "personal data",
        "data protection",
        "end-to-end encrypted",
        "e2ee",
        "zero knowledge",
        "zk",
    ],
    opensource: [
        "opensource",
        "open source",
        "oss",
        "github",
        "gitlab",
        "license",
        "licensing",
        "mit license",
        "apache license",
        "gpl",
        "maintainer",
        "maintainers",
        "contributor",
        "contributors",
    ],
    linux: [
        "linux",
        "unix",
        "ubuntu",
        "debian",
        "arch",
        "fedora",
        "kernel",
        "systemd",
        "terminal",
        "shell",
        "bash",
        "zsh",
        "command line",
        "cli",
    ],
    hardware: [
        "hardware",
        "chip",
        "chips",
        "cpu",
        "gpu",
        "nvidia",
        "amd",
        "intel",
        "arm",
        "risc-v",
        "riscv",
        "semiconductor",
        "semiconductors",
        "device",
        "devices",
        "electronics",
        "raspberry pi",
        "arduino",
        "firmware",
    ],
    science: [
        "science",
        "scientific",
        "physics",
        "chemistry",
        "biology",
        "math",
        "mathematics",
        "astronomy",
        "experiment",
        "experiments",
        "study",
        "studies",
        "paper",
        "papers",
        "journal",
        "discovery",
    ],
    health: [
        "health",
        "healthcare",
        "medical",
        "medicine",
        "doctor",
        "doctors",
        "hospital",
        "patient",
        "patients",
        "disease",
        "diseases",
        "mental health",
        "therapy",
        "drug",
        "drugs",
        "clinical",
    ],
    biotech: [
        "biotech",
        "bio",
        "biology",
        "genomics",
        "genome",
        "genetic",
        "genetics",
        "dna",
        "rna",
        "protein",
        "proteins",
        "crispr",
        "drug discovery",
        "clinical trial",
        "clinical trials",
        "pharma",
        "pharmaceutical",
    ],
    crypto: [
        "crypto",
        "cryptocurrency",
        "bitcoin",
        "ethereum",
        "blockchain",
        "web3",
        "wallet",
        "wallets",
        "token",
        "tokens",
        "defi",
        "smart contract",
        "smart contracts",
        "nft",
        "nfts",
        "solana",
        "stablecoin",
        "stablecoins",
    ],
    business: [
        "business",
        "company",
        "companies",
        "market",
        "markets",
        "enterprise",
        "revenue",
        "sales",
        "customer",
        "customers",
        "pricing",
        "strategy",
        "management",
        "acquisition",
        "merger",
    ],
    startups: [
        "startup",
        "startups",
        "founder",
        "founders",
        "cofounder",
        "co-founder",
        "yc",
        "y combinator",
        "mvp",
        "saas",
        "bootstrapped",
        "bootstrapping",
        "indie hacker",
        "indie hackers",
    ],
    funding: [
        "funding",
        "fundraise",
        "fundraising",
        "raised",
        "investment",
        "investor",
        "investors",
        "vc",
        "venture capital",
        "seed round",
        "series a",
        "series b",
        "valuation",
        "ipo",
    ],
    career: [
        "career",
        "careers",
        "job",
        "jobs",
        "hiring",
        "interview",
        "interviews",
        "resume",
        "salary",
        "promotion",
        "work",
        "workplace",
        "remote work",
        "layoff",
        "layoffs",
        "internship",
    ],
    productivity: [
        "productivity",
        "workflow",
        "workflows",
        "notes",
        "note taking",
        "todo",
        "tasks",
        "calendar",
        "automation",
        "focus",
        "time management",
        "habits",
        "personal knowledge management",
        "pkm",
    ],
    design: [
        "design",
        "ui",
        "ux",
        "user interface",
        "user experience",
        "figma",
        "typography",
        "visual design",
        "product design",
        "interaction design",
        "accessibility",
        "a11y",
    ],
    tools: [
        "tools",
        "tooling",
        "tool",
        "cli",
        "sdk",
        "framework",
        "library",
        "libraries",
        "package",
        "packages",
        "plugin",
        "plugins",
        "extension",
        "extensions",
        "editor",
        "ide",
        "vscode",
    ],
    performance: [
        "performance",
        "speed",
        "fast",
        "faster",
        "slow",
        "latency",
        "optimization",
        "optimisation",
        "optimize",
        "optimise",
        "benchmark",
        "benchmarks",
        "scaling",
        "scale",
        "memory",
        "cache",
        "caching",
    ],
    browsers: [
        "browser",
        "browsers",
        "chrome",
        "firefox",
        "safari",
        "edge browser",
        "chromium",
        "webkit",
        "extension",
        "browser extension",
        "webextensions",
    ],
    gaming: [
        "gaming",
        "game",
        "games",
        "game dev",
        "gamedev",
        "game development",
        "unity",
        "unreal",
        "steam",
        "console",
        "xbox",
        "playstation",
        "nintendo",
    ],
    media: [
        "media",
        "video",
        "videos",
        "audio",
        "music",
        "podcast",
        "podcasts",
        "streaming",
        "youtube",
        "film",
        "movie",
        "movies",
        "journalism",
        "news",
        "newsletter",
    ],
    education: [
        "education",
        "learning",
        "learn",
        "course",
        "courses",
        "tutorial",
        "tutorials",
        "school",
        "university",
        "college",
        "teaching",
        "students",
        "study",
        "studying",
    ],
    research: [
        "research",
        "researcher",
        "researchers",
        "paper",
        "papers",
        "study",
        "studies",
        "experiment",
        "experiments",
        "dataset",
        "datasets",
        "survey",
        "analysis",
        "arxiv",
    ],
    robotics: [
        "robotics",
        "robot",
        "robots",
        "drone",
        "drones",
        "autonomous",
        "automation",
        "humanoid",
        "actuator",
        "sensor",
        "sensors",
    ],
    space: [
        "space",
        "spacex",
        "nasa",
        "rocket",
        "rockets",
        "satellite",
        "satellites",
        "orbit",
        "mars",
        "moon",
        "astronomy",
        "telescope",
    ],
    climate: [
        "climate",
        "climate change",
        "environment",
        "environmental",
        "energy",
        "renewable",
        "renewables",
        "solar",
        "wind power",
        "carbon",
        "emissions",
        "sustainability",
    ],
    politics: [
        "politics",
        "political",
        "government",
        "policy",
        "regulation",
        "regulations",
        "election",
        "elections",
        "lawmakers",
        "congress",
        "senate",
        "democracy",
    ],
    economics: [
        "economics",
        "economy",
        "inflation",
        "recession",
        "market",
        "markets",
        "trade",
        "finance",
        "financial",
        "bank",
        "banking",
        "interest rates",
        "gdp",
    ],
    legal: [
        "legal",
        "law",
        "lawsuit",
        "lawsuits",
        "court",
        "copyright",
        "patent",
        "patents",
        "trademark",
        "regulation",
        "compliance",
        "antitrust",
    ],
    culture: [
        "culture",
        "society",
        "social",
        "history",
        "philosophy",
        "language",
        "writing",
        "books",
        "book",
        "art",
        "community",
        "communities",
    ],
    "show-hn": [
        "show hn",
        "show hacker news",
        "show-hn",
    ],
    "ask-hn": [
        "ask hn",
        "ask hacker news",
        "ask-hn",
    ],
    launches: [
        "launch",
        "launches",
        "launched",
        "launching",
        "release",
        "released",
        "announcement",
        "announcing",
        "introducing",
        "new product",
    ],
};

let tagsLoaded = false;
let allowedTags = new Set<string>();

function buildTagPatterns(tags: Tag[]) {
    allowedTags = new Set(tags.map((tag) => tag.tagName.toLowerCase()));

    return tags.flatMap((tag) => {
        const tagName = tag.tagName.toLowerCase();
        const aliases = tagAliases[tagName] ?? [tagName];

        return aliases.map((alias) => {
            return {
                name: tagName,
                patterns: [alias],
            };
        });
    });
}

async function parseFilterTags() {
    if (tagsLoaded) {
        return;
    }

    const tags = await fetchFilterTags();
    const tagPatterns = buildTagPatterns(tags);

    wink.learnCustomEntities(tagPatterns);

    tagsLoaded = true;
}

function addFallbackMatches(text: string, hits: Set<string>) {
    const normalizedText = text.toLowerCase();

    for (const [tagName, aliases] of Object.entries(tagAliases)) {
        if (!allowedTags.has(tagName)) {
            continue;
        }

        for (const alias of aliases) {
            if (normalizedText.includes(alias.toLowerCase())) {
                hits.add(tagName);
                break;
            }
        }
    }
}

export default async function extractTagsFromText(text: string): Promise<string[]> {
    await parseFilterTags();

    const doc = wink.readDoc(text);
    const matches = doc.customEntities().out(its.detail) as CustomEntityMatch[];

    const hits = new Set<string>();

    for (const match of matches) {
        const tagName = match.type.toLowerCase();

        if (allowedTags.has(tagName)) {
            hits.add(tagName);
        }
    }

    addFallbackMatches(text, hits);

    return [...hits];
}